# Generated by Django 4.1 on 2022-08-14 19:05
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ansuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='termos_uso',
            field=models.CharField(choices=[(False, 'Recusar'), (True, 'Aceitar')], max_length=5, verbose_name='Termos de Uso'),
        ),
    ]
