# Generated by Django 4.1 on 2022-08-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansuz', '0002_alter_usuario_termos_uso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
