# Generated by Django 4.1 on 2022-08-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansuz', '0005_area_planocurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planocurso',
            name='status',
            field=models.CharField(choices=[('1', 'APROVADO'), ('2', 'PENDENTE DE APROVAÇÃO'), ('3', 'RECUSADO')], default='2', max_length=1, verbose_name='Status do Curso'),
        ),
    ]
