# Generated by Django 4.1 on 2022-08-15 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansuz', '0006_alter_planocurso_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocurso',
            name='prof_responsavel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='planos_curso',
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
