# Generated by Django 4.1 on 2022-08-20 15:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('ansuz', '0008_alter_planocurso_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicoaula',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topicoaula',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 20, 12, 30, 14, 813628)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicoaula',
            name='text_rendered',
            field=markdownfield.models.RenderedMarkdownField(default='Digite a descrição. Esse campo permite o uso de Markdown.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topicoaula',
            name='descricao',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do documento')),
                ('pdf', models.FileField(upload_to='Tauany/LAIS/Segunda-Fase-LAIS/ansuz/documentos', verbose_name='PDF')),
                ('codigo_verificador', models.CharField(max_length=8, verbose_name='Código Verificador')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('plano_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='ansuz.planocurso')),
            ],
        ),
    ]
