# Generated by Django 4.1 on 2022-08-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansuz', '0009_topicoaula_atualizado_em_topicoaula_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='pdf',
            field=models.FileField(upload_to='Tauany/Projeto-LAIS/Segunda-Fase-LAIS/ansuz/documentos', verbose_name='PDF'),
        ),
    ]
