# Generated by Django 4.1 on 2022-08-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansuz', '0011_remove_certificado_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='Tauany/Projeto-LAIS/Segunda-Fase-LAIS/ansuz/documentos', verbose_name='PDF'),
        ),
    ]
